# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('hotel', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('value', models.IntegerField(default=0)),
                ('nights', models.IntegerField(default=0)),
                ('departure', models.TimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Location')),
            ],
        ),
    ]
