# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('phone2', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('email', models.CharField(max_length=128)),
                ('email2', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
