# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fio',
        ),
    ]
