# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20171005_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fio',
            new_name='name',
        ),
    ]
