# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171005_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour_discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tour_value',
        ),
    ]
